# Use root/example as user/password credentials
version: '3.1'

services:

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: DemoAppUsers
            MYSQL_USER: authService
            MYSQL_PASSWORD: authServicePassword
        volumes:
          - /var/lib/mysql
              

    adminer:
        image: adminer
        ports:
            - 8080:8080
            
    auth:
        image: authserver:demo
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: DemoAppUsers
            MYSQL_USER: authService
            MYSQL_PASSWORD: authServicePassword
        depends_on:
          - db
        ports:
          - 8081:8080
          - 8082:80
      
    mongo:
        image: mongo
        ports:
          - 27017
        
    shock:
        image: shock
        depends_on:
          - mongo
        entrypoint:
          - /go/bin/shock-server
          - --conf
          - /shock-config/shock-server.cfg 
        volumes:
          - /Users/Andi/Development/Shock/shock-server.container.cfg:/shock-config/shock-server.cfg 
          - /Users/Andi/Development/Shock/log:/var/log/shock 
          - /Users/Andi/Development/Shock/data:/usr/local/shock
        ports:
          - 7445:7445
          - 8083:80
          
          
    shock-browser:
        image: shock:browser
        depends_on:
          - shock
          - auth      
    nginx:
        image: nginx
        depends_on:
          - shock
          - adminer
          - auth
        ports:
          - 8001:8001 
        volumes: 
          - /Users/Andi/Development/github/App-Service-Stack/Services/nginx/conf/ass-demo.conf:/etc/nginx/conf.d/ass.conf:ro 
          - /Users/Andi/Development/github/App-Service-Stack/Services/nginx/logs/error.log:/var/log/nginx/error.log       
          

          
            